
spring:
  application:
    name: zuul-server-service
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    products:
      service-id: products-service
      path: /product-service/**
    items:
      service-id: item-service
      path: /item-service/**
    user:
      service-id: user-service
      path: /user-service/**
    oauth:
      service-id: oauth-service
      path: /api/security/**
      sensitive-headers: Cookie,Set-Cookie

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000