

spring:
  application:
    name: user-service

server:
  port: 5010

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    status-page-url-path: /swagger-ui.html

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


logging:
  level:
    org:
      hibernate:
        SQL: debug